[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "drsai_ext"
license = "MIT"
dynamic = ["version"]
description = "This is the extend packages for the dr.sai project."
readme = "README.md"
requires-python = ">=3.11"
keywords = ["drsai", "agent", "multi-agent", "scientific-computing"]
authors = [
    { name = "hepai" }
]
urls = { "Homepage" = "https://github.com/hepaihub/drsai" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "drsai",
]

[project.optional-dependencies]
mcp = [
    "mcp",
]


[tool.hatch.metadata]
allow-direct-references = true

[tool.pyright]
include = ["src", "tests"]
exclude = []
typeCheckingMode = "off"
reportUnnecessaryIsInstance = false
reportMissingTypeStubs = false


[tool.hatch.build.targets.wheel]
include-package-data = true
packages = [
    "src/drsai_ext",
    ]

[tool.hatch.version]
path = "src/drsai_ext/version.py"